export const FETCH_LIST_PRODUCTTYPE = 'prt/FETCH_LIST_PRODUCTTYPE';
export const FETCH_LIST_PRODUCTTYPE_SUCCESS = 'prt/FETCH_LIST_PRODUCTTYPE_SUCCESS';
export const ADD_PRODUCTTYPE = 'prt/ADD_PRODUCTTYPE';
export const ADD_PRODUCTTYPE_SUCCESS = 'prt/ADD_PRODUCTTYPE_SUCCESS';
export const DELETE_PRODUCTTYPE = 'prt/DELETE_PRODUCTTYPE';
export const DELETE_PRODUCTTYPE_SUCCESS = 'prt/DELETE_PRODUCTTYPE_SUCCESS';
export const UPDATE_PRODUCTTYPE ='prt/UPDATE_PRODUCTTYPE';